import React from 'react';
import { ShieldCheck, Lock, Sparkles, FileText, Layers, Database, Cpu, Zap } from 'lucide-react';

export const FeaturesSection: React.FC = () => {
  const features = [
    {
      title: 'Supabase Cloud Persistence',
      description: 'Your profiles, project attachments, activity logs, and progress state are securely stored in Supabase with RLS.',
      icon: <Database className="w-6 h-6 text-blue-600" />,
    },
    {
      title: 'Plagiarism Audit Guarantee',
      description: 'Every deliverable generated by our agents includes an originality checklist ensuring academic standard compliance.',
      icon: <ShieldCheck className="w-6 h-6 text-emerald-600" />,
    },
    {
      title: 'Multi-File Format Support',
      description: 'Upload PDF, Word (DOCX), PowerPoint (PPTX), Excel (XLSX), ZIP, RAR, and code files up to 20MB per attachment.',
      icon: <FileText className="w-6 h-6 text-purple-600" />,
    },
    {
      title: 'Role-Based Control',
      description: 'Built-in support for Student, Internal Agent/Freelancer, and Admin access levels with protected route guards.',
      icon: <Lock className="w-6 h-6 text-indigo-600" />,
    },
    {
      title: 'Pre-Assessment Engine',
      description: 'Provides instant estimated turnaround days, complexity breakdown, and suggested agent before project submission.',
      icon: <Cpu className="w-6 h-6 text-amber-600" />,
    },
    {
      title: 'Real-Time Progress Tracking',
      description: 'Visual step-by-step progress tracking from initial submission to final review and deliverable download.',
      icon: <Zap className="w-6 h-6 text-sky-600" />,
    },
  ];

  return (
    <section id="services" className="py-16 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto mb-12 space-y-2">
          <span className="px-3 py-1 rounded-full bg-blue-100 text-blue-700 text-xs font-bold uppercase tracking-wider">
            Platform Capabilities
          </span>
          <h2 className="mt-4 text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
            Built for Scale & Academic Precision
          </h2>
          <p className="text-slate-600 text-sm sm:text-base">
            Modern SaaS architecture powered by React, Tailwind CSS, and Supabase integration.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feat, i) => (
            <div
              key={i}
              className="bg-white rounded-2xl border border-slate-200/80 p-6 shadow-xs hover:shadow-md transition-shadow"
            >
              <div className="p-3 rounded-2xl bg-blue-50/80 w-fit mb-4 border border-blue-100">
                {feat.icon}
              </div>
              <h3 className="text-base font-bold text-slate-900 mb-2">{feat.title}</h3>
              <p className="text-xs text-slate-600 leading-relaxed">{feat.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};