import { AIAgent } from '../types';

export const AI_AGENTS: AIAgent[] = [
  {
    id: 'agent-doc',
    name: 'Documentation Assistant',
    specialization: 'SRS & System Architecture',
    description: 'Generates detailed Software Requirement Specifications, ER diagrams, data flow diagrams, and IEEE standard documentation.',
    iconName: 'FileCode2',
    badge: 'SRS Specialist',
    rating: 4.9,
    tasksCompleted: 342,
    status: 'Available',
    supportedCategories: ['documentation-srs', 'fyp-thesis'],
  },
  {
    id: 'agent-prog',
    name: 'Programming Assistant',
    specialization: 'Full Stack & Algorithms',
    description: 'Generates production-grade clean code, debugs complex algorithms, builds web/mobile apps, and writes automated tests.',
    iconName: 'Code2',
    badge: 'Senior Developer',
    rating: 4.95,
    tasksCompleted: 612,
    status: 'Available',
    supportedCategories: ['programming-code', 'data-analysis'],
  },
  {
    id: 'agent-pres',
    name: 'Presentation Assistant',
    specialization: 'Slide Decks & Speaker Notes',
    description: 'Creates high-impact presentation slides with structured bullet points, diagrams, visual hierarchy, and defense speaker prompts.',
    iconName: 'Presentation',
    badge: 'Visual Design Expert',
    rating: 4.88,
    tasksCompleted: 298,
    status: 'Available',
    supportedCategories: ['presentation-deck'],
  },
  {
    id: 'agent-res',
    name: 'Research Assistant',
    specialization: 'Literature Review & Citation',
    description: 'Scours academic databases, summarizes peer-reviewed journals, structures lit reviews, and formats citations in APA/IEEE.',
    iconName: 'Search',
    badge: 'Academic Scholar',
    rating: 4.92,
    tasksCompleted: 410,
    status: 'Available',
    supportedCategories: ['research-paper', 'fyp-thesis'],
  },
  {
    id: 'agent-assign',
    name: 'Assignment Assistant',
    specialization: 'Essays & Case Studies',
    description: 'Drafts comprehensive essays, analyzes complex business case studies, and solves step-by-step academic coursework.',
    iconName: 'PenTool',
    badge: 'Coursework Expert',
    rating: 4.85,
    tasksCompleted: 366,
    status: 'Available',
    supportedCategories: ['assignment-essay'],
  },
  {
    id: 'agent-stats',
    name: 'Data Analysis Assistant',
    specialization: 'Python, R & SPSS Statistics',
    description: 'Processes complex datasets, generates statistical visual charts, performs regression/ANOVA analysis, and interprets findings.',
    iconName: 'LineChart',
    badge: 'Statistics Specialist',
    rating: 4.91,
    tasksCompleted: 215,
    status: 'Available',
    supportedCategories: ['data-analysis', 'research-paper'],
  },
];
