import { Profile, Project, Notification, ActivityLog, Comment } from '../types';

export const INITIAL_DEMO_STUDENT: Profile = {
  id: 'usr-student-001',
  full_name: 'Ayesha Khan',
  email: 'student@studentassistant.edu',
  phone: '+1 (555) 234-5678',
  role: 'student',
  profile_photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
  created_at: '2026-01-15T08:30:00Z',
  institution: 'Stanford University',
  academic_degree: 'B.S. Computer Science (Senior Year)',
};

export const INITIAL_DEMO_FREELANCER: Profile = {
  id: 'usr-freelancer-001',
  full_name: 'Dr. Marcus Vance (Agent Lead)',
  email: 'freelancer@studentassistant.edu',
  phone: '+1 (555) 987-6543',
  role: 'freelancer',
  profile_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
  created_at: '2025-11-10T10:00:00Z',
  institution: 'MIT AI Lab',
  academic_degree: 'Ph.D. Computer Science',
};

export const INITIAL_DEMO_ADMIN: Profile = {
  id: 'usr-admin-001',
  full_name: 'System Admin',
  email: 'admin@studentassistant.edu',
  phone: '+1 (555) 000-1122',
  role: 'admin',
  profile_photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300',
  created_at: '2025-01-01T00:00:00Z',
  institution: 'Student Assistant HQ',
  academic_degree: 'M.S. Systems Management',
};

export const INITIAL_MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    student_id: 'usr-student-001',
    student_name: 'Ayesha Khan',
    title: 'Smart Attendance System using Facial Recognition (FYP)',
    description: 'Final Year Project complete documentation including SRS document, ER diagrams, system architecture diagrams, and Python OpenCV implementation code.',
    category: 'FYP & Thesis Writing',
    deadline: '2026-08-15',
    budget: 150,
    status: 'In Progress',
    priority: 'High',
    assigned_agent: 'Documentation Agent',
    progress_percentage: 65,
    created_at: '2026-07-20T10:15:00Z',
    updated_at: '2026-07-27T14:20:00Z',
    files: [
      {
        id: 'file-001',
        project_id: 'proj-001',
        file_name: 'Smart_Attendance_SRS_v1.docx',
        file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        file_size: 2450000,
        file_type: 'application/docx',
        uploaded_by: 'Documentation Agent',
        created_at: '2026-07-22T11:00:00Z',
      },
      {
        id: 'file-002',
        project_id: 'proj-001',
        file_name: 'System_Architecture_Diagram.png',
        file_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
        file_size: 1120000,
        file_type: 'image/png',
        uploaded_by: 'Documentation Agent',
        created_at: '2026-07-24T09:30:00Z',
      },
    ],
  },
  {
    id: 'proj-002',
    student_id: 'usr-student-001',
    student_name: 'Ayesha Khan',
    title: 'E-Commerce React & Node.js API Microservices',
    description: 'Building a scalable React client with Express microservices backend, JWT authentication, and REST API routes for payment integration.',
    category: 'Programming & Software Development',
    deadline: '2026-08-05',
    budget: 120,
    status: 'In Progress',
    priority: 'Urgent',
    assigned_agent: 'Programming Agent',
    progress_percentage: 60,
    created_at: '2026-07-22T14:00:00Z',
    updated_at: '2026-07-27T18:00:00Z',
    files: [
      {
        id: 'file-003',
        project_id: 'proj-002',
        file_name: 'API_Requirements.pdf',
        file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        file_size: 850000,
        file_type: 'application/pdf',
        uploaded_by: 'usr-student-001',
        created_at: '2026-07-22T14:00:00Z',
      }
    ],
  },
  {
    id: 'proj-003',
    student_id: 'usr-student-001',
    student_name: 'Ayesha Khan',
    title: 'Literature Review: Generative AI in Higher Education',
    description: 'A 4,000-word systematic literature review synthesizing 25 peer-reviewed papers on AI adoption, ethics, and assessment integrity in universities.',
    category: 'Research Paper & Literature Review',
    deadline: '2026-08-20',
    budget: 90,
    status: 'Review',
    priority: 'Medium',
    assigned_agent: 'Research Agent',
    progress_percentage: 90,
    created_at: '2026-07-18T09:00:00Z',
    updated_at: '2026-07-26T16:45:00Z',
    files: [
      {
        id: 'file-004',
        project_id: 'proj-003',
        file_name: 'LitReview_Draft_v2.pdf',
        file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        file_size: 3100000,
        file_type: 'application/pdf',
        uploaded_by: 'Research Agent',
        created_at: '2026-07-26T16:00:00Z',
      },
    ],
  },
  {
    id: 'proj-004',
    student_id: 'usr-student-001',
    student_name: 'Ayesha Khan',
    title: 'AI in Healthcare Slide Deck & Defense Notes',
    description: '20-slide presentation deck with high-resolution graphics, speaker notes, and anticipated Q&A for final course defense.',
    category: 'Presentation & Defense Decks',
    deadline: '2026-07-10',
    budget: 60,
    status: 'Completed',
    priority: 'Medium',
    assigned_agent: 'Presentation Agent',
    progress_percentage: 100,
    created_at: '2026-07-02T12:00:00Z',
    updated_at: '2026-07-08T15:00:00Z',
    files: [
      {
        id: 'file-005',
        project_id: 'proj-004',
        file_name: 'AI_Healthcare_Presentation.pptx',
        file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        file_size: 5400000,
        file_type: 'application/pptx',
        uploaded_by: 'Presentation Agent',
        created_at: '2026-07-08T15:00:00Z',
      },
    ],
  },
  {
    id: 'proj-005',
    student_id: 'usr-student-002',
    student_name: 'Zainab Ahmed',
    title: 'Machine Learning Sentiment Analysis for Social Media Data',
    description: 'Looking for an academic assistant to build a Python Scikit-Learn / PyTorch sentiment analysis model trained on Twitter & Reddit datasets, with full research methodology explanation for my CS thesis.',
    category: 'Data Analysis & Statistics',
    deadline: '2026-08-25',
    budget: 180,
    status: 'Submitted',
    priority: 'High',
    required_skills: ['Python', 'PyTorch', 'NLTK', 'Data Analysis', 'Scikit-Learn'],
    proposals_count: 3,
    progress_percentage: 0,
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'proj-006',
    student_id: 'usr-student-003',
    student_name: 'Bilal Hassan',
    title: 'Mobile Health App Flutter & Firebase Prototype',
    description: 'Need assistance creating a clean Flutter cross-platform mobile app interface with Firebase Authentication, Firestore database integration, and patient appointment booking screens.',
    category: 'Programming & Software Development',
    deadline: '2026-08-30',
    budget: 250,
    status: 'Submitted',
    priority: 'Urgent',
    required_skills: ['Flutter', 'Dart', 'Firebase', 'Mobile UI', 'REST API'],
    proposals_count: 5,
    progress_percentage: 0,
    created_at: '2026-08-03T14:20:00Z',
  },
  {
    id: 'proj-007',
    student_id: 'usr-student-004',
    student_name: 'Hassan Raza',
    title: 'IEEE Conference Paper on Quantum Cryptography Security',
    description: 'Academic assistance required to structure, proofread, and format a 6-page double-column IEEE template research paper focusing on post-quantum cryptographic algorithms.',
    category: 'Research Paper & Literature Review',
    deadline: '2026-08-28',
    budget: 140,
    status: 'Submitted',
    priority: 'Medium',
    required_skills: ['IEEE Formatting', 'LaTeX', 'Cryptography', 'Academic Writing'],
    proposals_count: 2,
    progress_percentage: 0,
    created_at: '2026-08-05T09:15:00Z',
  },
  {
    id: 'proj-008',
    student_id: 'usr-student-005',
    student_name: 'Fatima Malik',
    title: 'Software Engineering FYP Chapter 4 & 5 Discussion',
    description: 'Need help writing Chapter 4 (System Implementation & Testing Results) and Chapter 5 (Conclusion & Future Work) for my Software Engineering undergraduate Final Year Project.',
    category: 'FYP & Thesis Writing',
    deadline: '2026-09-05',
    budget: 200,
    status: 'Submitted',
    priority: 'High',
    required_skills: ['FYP Writing', 'Software Testing', 'System Documentation'],
    proposals_count: 4,
    progress_percentage: 0,
    created_at: '2026-08-08T11:00:00Z',
  },
];

export const INITIAL_MOCK_PROPOSALS = [
  {
    id: 'prop-001',
    project_id: 'proj-001',
    project_title: 'Smart Attendance System using Facial Recognition (FYP)',
    project_category: 'FYP & Thesis Writing',
    project_budget: 150,
    project_deadline: '2026-08-15',
    freelancer_id: 'usr-freelancer-001',
    freelancer_name: 'Dr. Marcus Vance (Agent Lead)',
    freelancer_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    cover_letter: 'I have over 8 years of experience in computer vision, Python OpenCV, and academic IEEE paper writing. I can assist you in providing high quality IEEE SRS documentation, ER diagrams, and clean modular Python implementation code.',
    proposed_price: 150,
    estimated_days: 12,
    status: 'Accepted' as const,
    created_at: '2026-07-21T08:00:00Z',
  },
  {
    id: 'prop-002',
    project_id: 'proj-005',
    project_title: 'Machine Learning Sentiment Analysis for Social Media Data',
    project_category: 'Data Analysis & Statistics',
    project_budget: 180,
    project_deadline: '2026-08-25',
    freelancer_id: 'usr-freelancer-001',
    freelancer_name: 'Dr. Marcus Vance (Agent Lead)',
    freelancer_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    cover_letter: 'As a PhD in Computer Science specializing in NLP and Machine Learning, I can build an end-to-end sentiment classification pipeline using PyTorch and Scikit-Learn along with comprehensive documentation.',
    proposed_price: 175,
    estimated_days: 10,
    status: 'Pending' as const,
    created_at: '2026-08-02T11:30:00Z',
  },
  {
    id: 'prop-003',
    project_id: 'proj-006',
    project_title: 'Mobile Health App Flutter & Firebase Prototype',
    project_category: 'Programming & Software Development',
    project_budget: 250,
    project_deadline: '2026-08-30',
    freelancer_id: 'usr-freelancer-001',
    freelancer_name: 'Dr. Marcus Vance (Agent Lead)',
    freelancer_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    cover_letter: 'I have developed multiple production Flutter applications with Firebase backends. I will deliver clean, well-commented Dart code with state management and security rules.',
    proposed_price: 240,
    estimated_days: 14,
    status: 'Pending' as const,
    created_at: '2026-08-04T16:00:00Z',
  },
];

export const INITIAL_MOCK_EARNINGS = [
  {
    id: 'earn-001',
    project_id: 'proj-004',
    project_title: 'AI in Healthcare Slide Deck & Defense Notes',
    freelancer_id: 'usr-freelancer-001',
    amount: 60,
    status: 'Available' as const,
    completed_at: '2026-07-08T15:00:00Z',
  },
  {
    id: 'earn-002',
    project_id: 'proj-003',
    project_title: 'Literature Review: Generative AI in Higher Education',
    freelancer_id: 'usr-freelancer-001',
    amount: 90,
    status: 'Pending' as const,
    completed_at: '2026-07-26T16:45:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    user_id: 'usr-student-001',
    title: 'Progress Update on FYP Documentation',
    message: 'Documentation Agent completed section 3: Software Requirements Specification & ER Diagrams.',
    is_read: false,
    type: 'status',
    created_at: '2026-07-28T03:15:00Z',
  },
  {
    id: 'notif-002',
    user_id: 'usr-student-001',
    title: 'File Uploaded',
    message: 'New deliverable file "Smart_Attendance_SRS_v1.docx" was uploaded to your project.',
    is_read: false,
    type: 'comment',
    created_at: '2026-07-27T14:20:00Z',
  },
  {
    id: 'notif-003',
    user_id: 'usr-student-001',
    title: 'Project Moved to Review',
    message: 'Your Literature Review project is currently undergoing plagiarism & quality audit.',
    is_read: true,
    type: 'status',
    created_at: '2026-07-26T16:45:00Z',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-001',
    user_id: 'usr-student-001',
    activity: 'New project submitted',
    details: 'E-Commerce React & Node.js API Microservices',
    created_at: '2026-07-22T14:00:00Z',
  },
  {
    id: 'act-002',
    user_id: 'usr-student-001',
    activity: 'AI Agent Assigned',
    details: 'Programming Agent assigned to project #proj-002',
    created_at: '2026-07-22T14:05:00Z',
  },
  {
    id: 'act-003',
    user_id: 'usr-student-001',
    activity: 'Project Completed',
    details: 'AI in Healthcare Slide Deck & Defense Notes marked as completed',
    created_at: '2026-07-08T15:00:00Z',
  },
];

export const INITIAL_MOCK_COMMENTS: Comment[] = [
  {
    id: 'cmt-001',
    project_id: 'proj-001',
    user_id: 'agent-doc',
    user_name: 'Documentation Agent',
    user_role: 'ai_agent',
    message: 'Hello Ayesha! I have analyzed your FYP requirements. I am drafting the Software Requirement Specification (SRS) following IEEE Std 830-1998 standards.',
    created_at: '2026-07-21T09:30:00Z',
    is_ai_generated: true,
  },
  {
    id: 'cmt-002',
    project_id: 'proj-001',
    user_id: 'usr-student-001',
    user_name: 'Ayesha Khan',
    user_role: 'student',
    message: 'Thanks! Please make sure to include the sequence diagrams for the facial recognition check-in flow.',
    created_at: '2026-07-21T11:15:00Z',
  },
  {
    id: 'cmt-003',
    project_id: 'proj-001',
    user_id: 'agent-doc',
    user_name: 'Documentation Agent',
    user_role: 'ai_agent',
    message: 'Understood. Sequence diagrams for Facial Feature Extraction, Match Verification, and Attendance Logging have been generated and attached.',
    created_at: '2026-07-24T09:35:00Z',
    is_ai_generated: true,
  },
];